
GET  http://localhost:5228

###

GET http://localhost:5228/api/categories?searchValue=clothing

###
POST http://localhost:5228/api/categories
Content-Type: application/json

{
    "categoryName":"electronics",
    "categoryDescription":"electronics"
}

###

PUT http://localhost:5228/api/categories/e40d2389-adcf-4943-9c60-fd2ff8e9f58a
Content-Type: application/json

{
    "categoryName":"Cloths2",
    "categoryDescription":"BD cloths2"
}

###

DELETE http://localhost:5228/api/categories/61a55cf2-be0d-4433-91c9-3dde50bf45c4


