
GET  http://localhost:5228

###

GET http://localhost:5228/api/categories

###
POST http://localhost:5228/api/categories

###

PUT http://localhost:5228/api/categories

###

DELETE http://localhost:5228/api/categories

###