
GET  http://localhost:5228

###

GET http://localhost:5228/api/categories

###
POST http://localhost:5228/api/categories
Content-Type: application/json
{
    CategoryName : "Electronics",
    CategoryDescription : "Devices and gadgets including phones, Laptops and other electronic equipment"
}

###

PUT http://localhost:5228/api/categories

###

DELETE http://localhost:5228/api/categories

###